### ISSUE TITLE
TickTick with Google calendar

### ISSUE THREAD

**Issue by Yousryi** [jonas0b1011001/GAS-ICS-Sync-CalAPIv3#15]
I'm using this script for syncing my TickTick to-do list with Google Calendar and it was great until it was summer last week timezone in tick-tick is GMT+2 but it's showing tasks in the calendar 1 hour earlier than it should be.
![Screenshot 2024-04-29 223131](https://github.com/jonas0b1011001/GAS-ICS-Sync-CalAPIv3/assets/168478580/a0ee8fde-d62f-45b7-bd01-e393e2346578)
I'm in Egypt which is GMT+2 but due to summer it becomes GMT+3 and I want to use the time zone normally.
Even if I turn timezones off and just set due date with no timezone it shows in my calendar earlier.

**Comment by jonas0b1011001** [comment]
Hi, this repo is not maintained, please check [https://github.com/derekantrican/GAS-ICS-Sync](https://github.com/derekantrican/GAS-ICS-Sync) for the latest version.

If the error persist after updating feel free to open an issue there and we will do our best to help you :)
