### ISSUE TITLE
Events without last-modified

### ISSUE THREAD

**Issue by tanoabeleyra** [jonas0b1011001/GAS-ICS-Sync-CalAPIv3#3]
I have events without `last-modified` neither `created` properties and because of that the next snippet updates all the events everytime:

```javascript
icsModDate = event.getFirstPropertyValue('last-modified') || event.getFirstPropertyValue('created') || Date.now();
calModDate = new Date(calendarEvents[index].updated);
if (icsModDate > calModDate){
  requiredAction = "update";
}
```

Also, Google API will complain when a lot of updates are made in a short period of time (throttling).

I think that, at a last resort, it should be handled as in the original repository, by checking if any property of the event changed: https://github.com/derekantrican/GAS-ICS-Sync/blob/master/Code.gs#L226

**Comment by jonas0b1011001** [comment]
I've been thinking about an efficient way to determine modified events for quite some time.
As far as i understand RFC 5545 the (indeed optional)'last-modified' property should indicate any update to an event.
I think checking for an update manually might be way more inefficient than relying on the client to use the proper ical standards..

Are the events you mentioned distinguishable by the 'dtstamp' property?

**Comment by jonas0b1011001** [comment]
> Also, Google API will complain when a lot of updates are made in a short period of time (throttling).

Never faced that issue. Could you provide the actual error message you are getting?

**Comment by tanoabeleyra** [comment]
> I think checking for an update manually might be way more inefficient than relying on the client to use the proper ical standards..

I know, that's why I said that it should be the last resort (if the event doesn't have a `last-modified`).

> Are the events you mentioned distinguishable by the 'dtstamp' property?

They have a `DTSTAMP`, this is an example (just the meaningful part):
```ics
BEGIN:VEVENT
UID:ai1ec-1390@foobar.com.ar
DTSTAMP:20190723T010514Z
DTSTART;TZID=America/Argentina/Buenos_Aires:20190720T170000
DTEND;TZID=America/Argentina/Buenos_Aires:20190720T183000
RDATE;TZID=America/Argentina/Buenos_Aires:20190721T170000
RDATE;TZID=America/Argentina/Buenos_Aires:20190722T170000
RDATE;TZID=America/Argentina/Buenos_Aires:20190723T170000
RDATE;TZID=America/Argentina/Buenos_Aires:20190724T170000
END:VEVENT
```

> Never faced that issue. Could you provide the actual error message you are getting?

This was the error: `Beim API-Aufruf von "calendar.events.update" ist dieser Fehler aufgetreten: Rate Limit Exceeded`. By the way, for some weird reason it's in German.

**Comment by jonas0b1011001** [comment]
I will see if it's a viable option. Manually checking recurrence will be a real pain though.

> This was the error: `Beim API-Aufruf von "calendar.events.update" ist dieser Fehler aufgetreten: Rate Limit Exceeded`. By the way, for some weird reason it's in German.

Latest commit hopefully get's rid of the error. I have not found any information on how many request are actually allowed in a given period of time so the delay intervals might need some adjustment.
(My Google Account is set to German, i don't know if/why this affects console output on your end..)
